fragment_downloaded_cb({"url": "python/testing.html#glibtest_fail", "fragment": "GLib.test_fail \nIndicates that a test failed. This function can be called multiple times from the same test. You can use this function if your test failed in a recoverable way. \nDo not use this function if the failure of a test could cause other tests to malfunction. \nCalling this function will not stop the test from running you need to return from the test function yourself. So you can produce additional diagnostic messages or even continue running the test. \nIf not called from inside a test this function does nothing. \nSince \n"});